### ISSUE TITLE
FR IGN maps don't work

### ISSUE THREAD

**Issue by Lambik** [tumic0/GPXSee-maps#25]
Hi,

When loading either of the two Europe - FR - IGN map xmls, I get the error:

```
---------------------------
GPXSee
---------------------------
Error loading map:

/Downloads/IGN-orthophotos.xml

Error downloading capabilities XML file
---------------------------
OK   
---------------------------

```

Maybe they changed url?

**Comment by sikmir** [comment]
Yes, looks like urls changed:
```
https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=10&TileCol=530&TileRow=365
https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=10&TileCol=536&TileRow=363
```

**Comment by tumic0** [comment]
http://professionnels.ign.fr/migration-geoportail
Probably a temporary issue, seems to work now.

**Comment by eddy-geek** [comment]
It's broken again?
```python
.local/share/gpxsee/maps/IGN-maps.xml: GEOGRAPHICALGRIDSYSTEMS.MAPS: layer not provided
```

ORTHO works, and I believe it's a permission issue again:

* https://wxs.ign.fr/pratique/geoportail/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=265&TileRow=184 → works
* https://wxs.ign.fr/pratique/geoportail/wmts?layer=GEOGRAPHICALGRIDSYSTEMS.MAPS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=265&TileRow=184 → `<Exception exceptionCode="MissingRights">No rights for this ressource or ressource does not exist</Exception>`
* https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=GEOGRAPHICALGRIDSYSTEMS.MAPS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=9&TileCol=265&TileRow=184 → works

but I tried to change to 	`<url>https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts</url>` without success

**Comment by eddy-geek** [comment]
For MOBAC [France-IGN-Rando.bsh](http://randochartreuse.free.fr/mobac2.x/mapsources/France/IGN/France-IGN-Rando.bsh) they add a User-Agent (in addition to the API key), not sure if that's what's making the difference.
