### ISSUE TITLE
Question: convert .kmz or .shp to .xml (map xsd schema)

### ISSUE THREAD

**Issue by timoteo7** [tumic0/GPXSee-maps#37]
Hello, have some wiki (tutorial),
to learn how to convert some files to .xml here (map xsd schema),
what software can convert this ?

example of files from Brazil:
[Some City - .kmz , .shp , .dwg](https://www1.londrina.pr.gov.br/index.php?option=com_content&view=article&id=20114&Itemid=1988)
[Some state - .shp ](http://www.sieg.go.gov.br/siegdownloads/)
[Organization with some Data - .dgn ](https://mapas.ibge.gov.br/bases-e-referenciais/bases-cartograficas/cartas)

**Comment by tumic0** [comment]
Try GDAL, it should be able to convert at least some of the data to a map format supported by GPXSee.

**Comment by tumic0** [comment]
Just to get sure - you can of course not convert the data to the XML map file as those are definitions for online sources. You have to convert to something like GeoTIFF.

**Comment by timoteo7** [comment]
thank you for answer,
i am trying this now:
https://gis.stackexchange.com/questions/298964/kmz-into-geotiff-gdal-translate

online XML map source can be in format other than:
`<format>image/jpgpng</format>`
???
