### ISSUE TITLE
new mapbox urls

### ISSUE THREAD

**Issue by MeisterP** [tumic0/GPXSee-maps#41]
Is it possible to add a map from https://docs.mapbox.com/playground/static/ ?

The url looks like `https://api.mapbox.com/styles/v1/mapbox/light-v10/static/-80.3318,39.1129,5,0/300x200?access_token=YOUR_MAPBOX_ACCESS_TOKEN`

using
`
<url>https://api.mapbox.com/styles/v1/mapbox/outdoors-v11/static/$x,$y,$z/300x200?access_token=YOUR_MAPBOX_ACCESS_TOKEN</url>`

results in a "Longitude must be between -180-180." error.

**Comment by tumic0** [comment]
`$x` and `$y` are not replaced by the longitude/latitude but by the [tile coordinates](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames). So this won't work.

You can theoretically generate such a static image, georeference it using a map file and then use it in GPXSee, but I do not see why anyone would do it, when he can use the mapbox tiles...

**Comment by MeisterP** [comment]
I think the mapbox tiles get depreciated?

> 
> Mapbox is deprecating support for Mapbox Studio Classic Styles on June 1st, 2020 and you’ve recently made requests using those styles. Here's a quick guide so you're prepared for these changes. 
> 
> As a reminder, you have not been able to modify these styles since March 31 and these styles stopped receiving map data updates in Q1 2018.
> 
> On June 1, we will no longer support requests to Studio Classic styles or projects from new apps and websites. Requests from your existing websites and apps will continue working for a period of time as we work with you to move off the service.
> 
> If you've already stopped using Studio classic styles in your web or mobile app, then please disregard the rest of this email.
> 
> 1. What are the benefits of upgrading my Classic styles?
> 
> Some of the immediate benefits of upgrading include: daily map data updates validated by Mapbox (Classic styles stopped receiving map data updates in Q1 2018), the ability to customize and style your maps with Style Components in Studio, and significantly improved load times and global reliability. After June 1, Mapbox will not be prioritizing operational improvements to the endpoints that serve Classic styles.
> 
> 2. Where can I see the Classic styles associated with my account?
> 
> If you’re using a custom classic style created via Studio Classic or a classic project created in Mapbox Editor, you can see your Classic styles listed here: https://studio.mapbox.com/classic/.
> 
> If you're receiving this email, but you don't see any styles listed at the above link, follow this migration guide to locate the styles used in your application. 
> 
> 3. How do I upgrade from Classic styles to modern Studio styles?
> 
> If you have an interactive slippy map, read our guide on migrating to the modern Static Tiles API. If you’re using a Classic style as a fallback for browsers that don’t support WebGL, use this tutorial to upgrade.
> 
> Note: the Static Tiles API can return 512x512 map tiles, which cover 4x the area of the 256x256 tiles associated with Classic styles. Be sure you include the tileSize: 512 and zoomOffset: -1 options so you don't incur 4x as many tile requests as necessary and so that your labels, icons, and other map features don't appear smaller than expected.
> 
> If you're using the Legacy Static Images API to embed static map images in your website or application, read our guide on migrating to the modern Static Images API.
>     
> If you need additional resources to help upgrade to modern Studio styles you can use our Developer Network and select the “Legacy Applications” skill in your search.
>     
> If you have any questions about the above, please reach out to our support team or your Technical Account Manager.
>

**Comment by MeisterP** [comment]
Mainly this part. As far as I understand, https://docs.mapbox.com/playground/static/ is the new "the modern Static Images API"

> If you're using the Legacy Static Images API to embed static map images in your website or application, read our guide on migrating to the modern Static Images API.

**Comment by tumic0** [comment]
Mapbox is going to close the Classic Styles (CartoCSS) based services, not vector tiles services as whole. Mapbox Studio (the "new" styles) and the vector tiles are their core business. The static images API is just a marginal service for very special purposes.

GPXSee does not use any Mapbox technology, except that it can render the Mapbox vector tiles which are part of Mapbox's "new" Mapbox Studio ecosystem. Even the styles used for styling the tiles are the "new" styles. However, as a hipster developer driven company with no care about backward compatibility (they have [dropped backward compatibility](https://github.com/mapbox/vector-tile-spec/issues/136) of the vector tiles with the "old" raster tiles because of a single byte), Mapbox is continually deprecating stuff, so the recent styles use a completely different "selection language" (property functions->expressions) so the newest styles won't work in GPXSee. The older one will however not stop working regardless if Mapbox removes their support from their services.

**Comment by MeisterP** [comment]
Thanks for your explanation. Much appreciated.
