### ISSUE TITLE
More tiles providers from leaflet-providers

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee-maps#45]
Hello,

I found that https://github.com/leaflet-extras/leaflet-providers provides a large number of tiles providers.
See https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js

Leaflet tiles url uses `s`, `z`, `x`, `y`, `r` variables. According to https://leafletjs.com/reference-1.4.0.html#tilelayer

> {s} means one of the available subdomains (used sequentially to help with browser parallel requests per domain limitation; subdomain values are specified in options; a, b or c by default, can be omitted), {z} — zoom level, {x} and {y} — tile coordinates. {r} can be used to add "@2x" to the URL to load retina tiles.

Maybe GPXSee-maps could provide same providers also.

Kind regards

PS : will need https://github.com/tumic0/GPXSee/issues/317

**Comment by scls19fr** [comment]
For the little story, I found [leaflet-providers](https://github.com/leaflet-extras/leaflet-providers) browsing at [MSFS2020-cockpit-companion](https://github.com/hankhank10/MSFS2020-cockpit-companion/) code.

MSFS2020-cockpit-companion have a nice [map overlay](https://github.com/tumic0/GPXSee/issues/178) feature with [OpenAIP](https://www.openaip.net/) map.

See https://github.com/hankhank10/MSFS2020-cockpit-companion/blob/5ee36a84408aded2fa8e5e9c5b13df95a11f1a39/templates/glass.html#L512-L520 for OpenAIP map

**Comment by tumic0** [comment]
Most of the leaflet sources are already here. From those that aren't, which one do you miss (and what exactly is so uniq on that source, if it is yet another OpenStreet map based map)?
