### ISSUE TITLE
Not an issue, but a request

### ISSUE THREAD

**Issue by jacanestro** [tumic0/GPXSee-maps#48]
Hi! 

I live in Gran Canaria in Canary Islands.
Would it be possible to create an online map from this website https://visor.grafcan.es/visorweb/ selecting the "Mapa Tompográfico 1:20000" map?
I see requests like these:
https://idecan3.grafcan.es/ServicioWMS/MT20?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=false&LAYERS=WMS_MT20&SRS=EPSG%3A32628&WIDTH=256&HEIGHT=256&STYLES=&BBOX=312735.5839256644%2C3088263.891265951%2C351827.53191637265%2C3127355.839256659
It looks like they are using WMS...

Thank you again in advance!

**Comment by tumic0** [comment]
Sure, you can make GPXSee maps from almost any WMS or WMTS service:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="WMS">
    <name>IDECanarias Mapa Topográfico</name>
    <url>https://idecan1.grafcan.es/ServicioWMS/MT20</url>
    <copyright>© GRAFCAN</copyright>
    <layer>WMS_MT20</layer>
    <crs>EPSG:32628</crs>
    <format>image/jpeg</format>
</map>
```
If the service provider allows it (from what I can translate using Google translate I'm not sure what the usage policy is...), I can add it to the map repository.

**Comment by jacanestro** [comment]
Wow!! That's wonderful! Thanks a lot.
Would you like me to contact them and ask for permission?

Regards.

**Comment by tumic0** [comment]
Would be nice, to have some official "ok" from them. From what I can understand from the website/WMS capabilities XML, the service is free but bulk downloads are forbidden (which is ok as GPXSee does not do bulk downloads). IDECanarias looks like some government organization, but I have no idea who/what GRAFCAN is which has copyright on the data.

**Comment by jacanestro** [comment]
Good morning Tumic!!


I have just received Grafcan reply to our question.

"Los servicios disponibles en la plataforma IDECanarias, son para ser utilizados por todos los usuarios sin animo de lucro. Toda la información disponible en el catalogo Web Map Service,. https://catalogo.idecanarias.es/geonetwork/srv/spa/catalog.search#/home"

The summary is that anyone can use all available services from IDECanarias for non-profit purposes.
So, you can upload the XML under ES, I suggest... ;-)

Thanks again for this great tool.

**Comment by tumic0** [comment]
maps added
