### ISSUE TITLE
Croatia topo map - error downloading capabilities xml file

### ISSUE THREAD

**Issue by zoom0** [tumic0/GPXSee-maps#49]
https://tumic0.github.io/GPXSee-maps/

HR-DOF.xml is working fine but HR-TK25.xml not.

with HR-TK25.xml i have gpxsee error loading map - error downloading capabilities xml file

please help

**Comment by tumic0** [comment]
Works for me. Even technically this makes no sense as both maps use the same WMS capabilities URL. What you have encountered was probably a temporary server issue, the server is evidently often overloaded. I have increased the tile size in the maps which makes the map loading more reliable in 7ffe013464a71e01096f44969d4958a8023d2c12, but during "rush hours" you will probably still see download errors.

**Comment by zoom0** [comment]
I still have same error at any time of the day/night. same is with new  512tile size xml I was just testing it now 
![xmlJPG](https://user-images.githubusercontent.com/47673527/109710337-d8a97c00-7b9d-11eb-8e71-a4dc8f1c9a18.JPG)

**Comment by zoom0** [comment]
testing on another comp same error. both computers windows 7 x64

**Comment by tumic0** [comment]
Well, the changed tile size won't have any effect on downloading the capabilities file. It helps when downloading the tiles. Did you try to clear the map cache? If this won't help, look into the cache directory "manually" and check if there is for example not a file, that can not be deleted due to access rights or so. The error may also be caused by GPXSee not being able to save the capabilities file.

If the second map works for you, the problem won't most probably be in the download itself as the URLs are the same.

**Comment by zoom0** [comment]
thank you I was try testing on another comp same error. both computers windows 7 x64

**Comment by tumic0** [comment]
Should be fixed in 50119747ccf647f586169b273ee1f1999da07ca2. The map name which is used for the tiles cache directory may not contain the `:` character, otherwise it won't work on Windows.

**Comment by zoom0** [comment]
not working for me, new error :(
![xml new](https://user-images.githubusercontent.com/47673527/109719998-c7666c80-7ba9-11eb-933f-0bfc66573570.JPG)

**Comment by tumic0** [comment]
Works fine for me, this time even on Windows (tested) ;-)
Did you update git/redownload the map from the [catalogue](https://tumic0.github.io/GPXSee-maps/), or modified it yourself?

**Comment by zoom0** [comment]
download from catalogue

tested now third computer win 7 32 bit an is working fine with DOF and TK25 xml

both 64 bit with 64 bit gpxsee not working. will try to install 32 bit version on 64 bit OS

**Comment by zoom0** [comment]
32 bit gpxsee installed on 64 bit win 7 ans IS WORKING fine now

**Comment by zoom0** [comment]
its not about gpxsee version. tested on comp no 2. 64 bit OS/64 bit gpxsee, new TK25.xml from catalogue is working, old TK25.xml from catalogue not working

**Comment by tumic0** [comment]
I have tested the 64b version (GPXSee 8.8) on 64b Windows 7 and Windows 10 and in both cases it works fine with the `HR-TK25.xml` map

**Comment by tumic0** [comment]
There must be something wrong in your map file.

**Comment by zoom0** [comment]
now is ok is working fine with latest xml from catalogue, thank you so much for help.
