### ISSUE TITLE
GPS position should prefer SatellitePositioningMethods else it is usually broken with Geclue

### ISSUE THREAD

**Issue by ppisa** [tumic0/GPXSee-maps#56]
GPS position should prefer SatellitePositioningMethods

When Geoclue 2 and gnss-share are used on Librem 5 phone and probably even on the other systems then incorrect position is obtained from QGeoPositionInfoSourceGeoclue2 plugin because GPXsee it does not require GCLUE_ACCURACY_LEVEL_EXACT. So only rough location pointing to the city center is provided. May it be it works on systems and plugins as serialnmea  which do not provide alternatives and full PositioningMethods selection and enumeration. But for general case, GPXSee setup of QGeoPositionInfoSource is deficient.

The fix is available in  my [zoom-by-pinch](https://github.com/ppisa/GPXSee/tree/zoom-by-pinch) branch. See https://github.com/ppisa/GPXSee/commit/f7e0282fda93be5ff64147f4a5a571df1b3a208b 

When the QGeoPositionInfoSource is correctly configured by `setPreferredPositioningMethods` for `QGeoPositionInfoSource::SatellitePositioningMethods` the location is tracked.

Be sure to check that the correct source is setup in `/etc/geoclue/geoclue.conf`.

Se section
```
[network-nmea]
enable=true
nmea-socket=/var/run/gnss-share.sock
```

Ensure that socket name matches unix socket path created
by `gnss-share` and that `[agent]` section `whitelist` includes `gpxsee`
and gpxsee section is provided
```
[gpxsee]
allowed=true
system=false
users=
```

Then GPXSee has chance to be used offline map GPS application. I use Garmin maps.

**Comment by tumic0** [comment]
Please note, that this is definitely not the right project to report such issues.
However, fixed in tumic0/GPXSee@d0e0ea32ab443348d240faf3a6aeb2d0971b136f.
