### ISSUE TITLE
show in file explorer or delete file function?

### ISSUE THREAD

**Issue by hal9000de** [tumic0/GPXSee-maps#61]
Hello,
This is the tool I've always been looking for! It's the IrfanView for GPS logs. It's perfect for browsing my GPX file archives.

Thanks for the tool!

If I could make suggestions for the tool? Would I like better keyboard shortcut support and a 'show in file explorer' or a direct file deletion functionality.

There are buttons in the toolbar to move through files in the folder, but I haven't found any shortcuts to do so. And if I come across 'garbage data' or something like that I have to look for them again in the file explorer to delete or move them.

Thanks again for this tool!
hal

**Comment by tumic0** [comment]
Well, GPXSee is not IrfanView for GPS logs but ACDSee for GPS logs :-), so the main shortcuts are like in ACDSee - space and backspace. You can see all the other shortcuts under Help->Keyboard controls and in the menu bars.
