### ISSUE TITLE
MapTiler broken?

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee-maps#62]
Is https://github.com/tumic0/GPXSee-maps/blob/master/World/MapTiler.tpl still working for you ?

```sh
curl https://raw.githubusercontent.com/tumic0/GPXSee-maps/master/World/MapTiler.tpl -o ~/.local/share/gpxsee/maps/maptiler.xml
sed -i 's/insert-your-apikey-here/rJU8f69pSsmhWM7EWEG3/g' ~/.local/share/gpxsee/maps/maptiler.xml
gpxsee
```

In the logs I get `https://api.maptiler.com/tiles/v3/2/1/1.pbf?key=rJU8f69pSsmhWM7EWEG3: Operation canceled` after what seems like a time-out ; but `curl https://api.maptiler.com/tiles/v3/2/1/1.pbf?key=rJU8f69pSsmhWM7EWEG3 -o a.pbf` works fine.

**Comment by tumic0** [comment]
Yes, it still works for me (although with a different API key).
